- type: entity
  parent: BaseItem
  id: GridConfigurator
  name: grid configurator
  description: Used to modify the name and station that a grid is associated with.
  components:
    - type: EmitSoundOnLand
      sound:
        path: /Audio/Items/multitool_drop.ogg
    - type: Sprite
      sprite: Objects/Tools/access_configurator.rsi
      state: icon
    - type: Item
      size: Small
    - type: Clothing
      sprite: Objects/Tools/access_configurator.rsi
      quickEquip: false
      slots:
        - Belt
    - type: GridConfig
      privilegedIdSlot:
        name: id-card-console-privileged-id
        ejectSound: /Audio/Machines/id_swipe.ogg
        insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
        ejectOnBreak: true
        swap: false
        whitelist:
          components:
          - IdCard
      denialSound:
        path: /Audio/Machines/custom_deny.ogg
      doAfter: 0.5
    - type: UserInterface
      interfaces:
        enum.GridConfigUiKey.Key:
          type: GridConfigBoundUserInterface
    - type: ActivatableUI
      key: enum.GridConfigUiKey.Key
      requiresComplex: true
      requireActiveHand: false
      singleUser: true
      inHandsOnly: true
    - type: ItemSlots
    - type: ContainerContainer
      containers:
        GridConfig-privilegedId: !type:ContainerSlot

- type: entity
  parent: BaseItem
  id: StationTagger
  name: faction tagger
  description: Used to link specific machines and structures with a station.
  components:
    - type: EmitSoundOnLand
      sound:
        path: /Audio/Items/multitool_drop.ogg
    - type: Sprite
      sprite: Objects/Tools/access_configurator.rsi
      state: icon
    - type: Item
      size: Small
    - type: Clothing
      sprite: Objects/Tools/access_configurator.rsi
      quickEquip: false
      slots:
        - Belt
    - type: StationTagger
      privilegedIdSlot:
        name: id-card-console-privileged-id
        ejectSound: /Audio/Machines/id_swipe.ogg
        insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
        ejectOnBreak: true
        swap: false
        whitelist:
          components:
          - IdCard
      denialSound:
        path: /Audio/Machines/custom_deny.ogg
      doAfter: 0.5
    - type: UserInterface
      interfaces:
        enum.StationTaggerUiKey.Key:
          type: StationTaggerBoundUserInterface
    - type: ActivatableUI
      key: enum.StationTaggerUiKey.Key
      requiresComplex: true
      requireActiveHand: false
      singleUser: true
      inHandsOnly: true
    - type: ItemSlots
    - type: ContainerContainer
      containers:
        StationTagger-privilegedId: !type:ContainerSlot


- type: entity
  parent: BaseItem
  id: StationGenesisDevice
  name: faction genesis device
  description: A one time use device which creates a new faction network which grids can be connected to.
  components:
    - type: EmitSoundOnLand
      sound:
        path: /Audio/Items/multitool_drop.ogg
    - type: Sprite
      sprite: Objects/Tools/access_configurator.rsi
      state: icon
    - type: Item
      size: Small
    - type: Clothing
      sprite: Objects/Tools/access_configurator.rsi
      quickEquip: false
      slots:
        - Belt
    - type: StationCreator
      privilegedIdSlot:
        name: id-card-console-privileged-id
        ejectSound: /Audio/Machines/id_swipe.ogg
        insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
        ejectOnBreak: true
        swap: false
        whitelist:
          components:
          - IdCard
      denialSound:
        path: /Audio/Machines/custom_deny.ogg
      doAfter: 0.5
    - type: UserInterface
      interfaces:
        enum.StationCreatorUiKey.Key:
          type: StationCreatorBoundUserInterface
    - type: ActivatableUI
      key: enum.StationCreatorUiKey.Key
      requiresComplex: true
      requireActiveHand: false
      singleUser: true
      inHandsOnly: true
    - type: ItemSlots
    - type: ContainerContainer
      containers:
        StationCreator-privilegedId: !type:ContainerSlot


- type: entity
  parent: BaseItem
  id: Invoice
  name: digital invoice
  description: A digital invoice which processes payments.
  components:
    - type: Sprite
      sprite: Objects/Misc/bureaucracy.rsi
      state: invoiceunpaid
    - type: Item
      size: Small
    - type: Invoice
    - type: UserInterface
      interfaces:
        enum.InvoiceUiKey.Key:
          type: InvoiceBoundUserInterface
    - type: ActivatableUI
      key: enum.InvoiceUiKey.Key
      requiresComplex: true
      requireActiveHand: false
      singleUser: true
    - type: PaperVisuals
    - type: Appearance
